# Use the official Node.js image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the Next.js app files from the host to the container
COPY . .

# Expose port 3000 for Next.js
EXPOSE 3000

# Default command to run the Next.js development server
CMD ["npm", "run", "dev"]
